apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubebeat-audio-service
  labels:
    app: kubebeat-audio-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubebeat-audio-service
  template:
    metadata:
      labels:
        app: kubebeat-audio-service
    spec:
      containers:
        - name: audio-service
          image: ghcr.io/rehab911/kubebeat/audio-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: github-registry-key
